# Data directories
data_dir = ""  # Directory holding all competition data

train_dir = bronze_train_dir = ""  # Directory location of training data (bronze)
test_dir = bronze_test_dir = ""  # Directory location of testing data (bronze)
sample_submission_dir = bronze_sample_submission_dir = (
    ""  # Directory location of sample submission (bronze)
)

silver_train_dir = ""  # Directory of silver state training data generated by leash_bio_ai\data\silver_state.py
silver_test_dir = ""  # Directory of silver state testing data generated by leash_bio_ai\data\silver_state.py

# Logger files
test_logger_file = ""  # Directory location of test logger used in 02_polars_pipeline_test.ipynb notebook
silver_logger_file = ""  # Directory of location of silver state data logger for the leash_bio_ai\data\silver_state.py script
